spring.application.name=digital-payment-management

#SPRING DATASOURCES
#jdbc config
spring.datasource.url=jdbc:${url}
spring.datasource.username=${UserName}
spring.datasource.password=${Password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hiberante config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}