spring.application.name=digital-payment-management

#SPRING DATASOURCES
spring.datasources.url=jdbc:mysql://localhost:3306/wallet?createDatabaseIfNotExist=true
spring.datasources.username=root
spring.datasources.password=Sesan@25
spring.datasources.driver-class-name=com.mysql.cj.jdbc.Driver

#SPRING JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect